import type { User, Post, Comment } from './types';

export const users: User[] = [
  {
    id: 'user-1',
    username: 'mona_lisa',
    name: 'Mona Lisa',
    avatarUrl: 'https://placehold.co/150x150.png',
    bio: 'Art enthusiast. Tech lover. In search of the perfect byte.',
    postsCount: 3,
    followersCount: 1302,
    followingCount: 150,
  },
  {
    id: 'user-2',
    username: 'vincent_van_draw',
    name: 'Vincent van Draw',
    avatarUrl: 'https://placehold.co/150x150.png',
    bio: 'Painting my world with code. One commit at a time.',
    postsCount: 2,
    followersCount: 2100,
    followingCount: 340,
  },
  {
    id: 'user-3',
    username: 'tech_tesla',
    name: 'Nicola Techsla',
    avatarUrl: 'https://placehold.co/150x150.png',
    bio: 'Innovator. Dreamer. Building the future.',
    postsCount: 1,
    followersCount: 5000,
    followingCount: 2,
  },
];

const mockComments: Comment[] = [
    {
      id: 'comment-1',
      text: 'This is an amazing shot!',
      user: { username: 'vincent_van_draw', avatarUrl: 'https://placehold.co/150x150.png' },
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
    },
    {
      id: 'comment-2',
      text: 'Love the colors here.',
      user: { username: 'tech_tesla', avatarUrl: 'https://placehold.co/150x150.png' },
      timestamp: new Date(Date.now() - 1000 * 60 * 2),
    },
];

export const initialPosts: Post[] = [
  {
    id: 'post-1',
    user: { username: 'mona_lisa', avatarUrl: 'https://placehold.co/150x150.png' },
    imageUrl: 'https://placehold.co/600x600.png',
    caption: 'Exploring the world through a new lens. Every day is a discovery.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    likes: 152,
    comments: mockComments,
    isLiked: false,
  },
  {
    id: 'post-2',
    user: { username: 'vincent_van_draw', avatarUrl: 'https://placehold.co/150x150.png' },
    imageUrl: 'https://placehold.co/600x600.png',
    caption: 'Starry nights and city lights. Finding beauty in the chaos.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    likes: 320,
    comments: [],
    isLiked: true,
  },
  {
    id: 'post-3',
    user: { username: 'mona_lisa', avatarUrl: 'https://placehold.co/150x150.png' },
    imageUrl: 'https://placehold.co/600x600.png',
    caption: 'Just another day in paradise. #blessed',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48),
    likes: 88,
    comments: [],
    isLiked: false,
  },
  {
    id: 'post-4',
    user: { username: 'tech_tesla', avatarUrl: 'https://placehold.co/150x150.png' },
    imageUrl: 'https://placehold.co/600x600.png',
    caption: 'The future is now.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72),
    likes: 1024,
    comments: [],
    isLiked: true,
  },
  {
    id: 'post-5',
    user: { username: 'vincent_van_draw', avatarUrl: 'https://placehold.co/150x150.png' },
    imageUrl: 'https://placehold.co/600x600.png',
    caption: 'Lost in the details.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96),
    likes: 451,
    comments: [],
    isLiked: false,
  },
  {
    id: 'post-6',
    user: { username: 'mona_lisa', avatarUrl: 'https://placehold.co/150x150.png' },
    imageUrl: 'https://placehold.co/600x600.png',
    caption: 'Coffee and code.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 120),
    likes: 234,
    comments: [],
    isLiked: false,
  },
];
